#!/bin/bash

# check if script is run as root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit 1
fi

# check if website argument is passed
if [ -z "$1" ]
  then echo "No argument supplied: ./add-website example.com (without the www.!)"
  exit 1
fi

# set domain
domain=$1

# set email address for in cert renewal .ini
email="your@email.com"

# set webroot path
wwwdir="/var/www/$domain/html"

# set nginx path
nginxfile="/etc/nginx/sites-available/$domain"

# create directory
mkdir -p $wwwdir

# create default welcome message
cat <<EOF > $wwwdir/index.php
<center>Welcome to www.$domain !</center>
EOF

# set user permissions
chown -R $USER:$USER $wwwdir

# write to nginx conf
# conf is made this way that (*.)example.com:80 (*.)example.com:443 is redirected to www.example.com:443
# change as you wish
cat <<EOF > $nginxfile
server {
        listen 80;
        listen 443 ssl;
        server_name .$domain;

        ssl_certificate /etc/letsencrypt/live/www.$domain/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/www.$domain/privkey.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';


        return 301 https://www.$domain\$request_uri;
}

server {
        listen 443 ssl;

        root /var/www/$domain/html;
        index index.php index.html index.htm;

        server_name www.$domain;

        ssl_certificate /etc/letsencrypt/live/www.$domain/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/www.$domain/privkey.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';

        location ~ /.well-known {
                allow all;
        }

        location / {
                try_files \$uri \$uri/ =404;
        }

        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
                root /usr/share/nginx/html;
        }

        location ~ \.php$ {
                try_files \$uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
                include fastcgi_params;
        }
}
EOF

# symlink it
ln -s $nginxfile /etc/nginx/sites-enabled/

# create the renew .ini
cat <<EOF > /usr/local/etc/$domain.ini
rsa-key-size = 4096

email = $email

domains = www.$domain, $domain

webroot-path = $wwwdir
EOF

# need to stop nginx before creating the certs
/usr/sbin/service nginx stop

# create the SSL certs!
/opt/letsencrypt/letsencrypt-auto certonly --standalone --webroot-path=$wwwdir -d www.$domain -d $domain

# reload nginx and we're done
/usr/sbin/service nginx start
